<a href="https://colab.research.google.com/github/pragyan27bit/ml-learning/blob/main/Day01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [162]:
import numpy as np

In [163]:
mylist = [1,2,3]
type(mylist)

list

In [164]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [193]:
np.arange(1,9,2) # creates an array from 0 till 9 excluded with a gap of 2
np.arange(0, 101, 20) # creates an array from 0 to 100 with a gap of 20

array([  0,  20,  40,  60,  80, 100])

In [166]:
np.zeros(5)
np.zeros((5,5)) # creates a matrix of 5 x 5 of all zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [167]:
np.ones(5) # creates a array of all elements as 1

array([1., 1., 1., 1., 1.])

In [168]:
np.linspace(0,10,5) # creates an array starting from 0 till 10 included and divides into 5 parts
np.linspace(0, 10 , 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [169]:
np.eye(5) # creates a diagonal matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [170]:
np.random.rand(2,5) # creates an array of random numbers from 0 to 1

array([[0.96990985, 0.83244264, 0.21233911, 0.18182497, 0.18340451],
       [0.30424224, 0.52475643, 0.43194502, 0.29122914, 0.61185289]])

In [171]:
np.random.randn(10) # creates an array of 10 random numbers

array([-0.42804606, -0.74240684, -0.7033438 , -2.13962066, -0.62947496,
        0.59772047,  2.55948803,  0.39423302,  0.12221917, -0.51543566])

In [172]:
np.random.randint(0, 100, 10) # creates an array of 10 random numbers between 0 and 100 excluded

array([20, 72, 38, 17,  3, 88, 59, 13,  8, 89])

In [173]:
np.random.seed(42) # set a particular set of numbers
np.random.rand(4) # output is always same because of seed

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [185]:
arr = np.random.randint(0, 100, 10)
arr.max() # returns the max value in the array
arr.argmax() # returns the index of the max value in the array
arr.min() # returns the min value in the array
arr.argmin() # returns the index of the min value in the array

np.int64(6)

In [217]:
arr[5] # return the value at index 8
arr[1:5] # returns a subarray from index 1 till 5 excluded
arr[:5] # returns a subarray from index 0 till 5 excluded
arr[5:] # returns a subarray from index 5 till end
arrnew = arr.reshape(2,5)
arrnew[0,3] # returns the value at given index
boolarr = arr > 5 # return a boolean array for given condition


array([34, 77, 80, 35, 49, 53])