<a href="https://colab.research.google.com/github/pragyan27bit/ml-learning/blob/main/Day01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]
type(mylist)

list

In [4]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [5]:
np.arange(1,9,2) # creates an array from 0 till 9 excluded with a gap of 2
np.arange(1, 101, 20)

array([ 1, 21, 41, 61, 81])

In [6]:
np.zeros(5)
np.zeros((5,5)) # creates a matrix of 5 x 5 of all zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(5) # creates a array of all elements as 1

array([1., 1., 1., 1., 1.])

In [8]:
np.linspace(0,10,5) # creates an array starting from 0 till 10 included and divides into 5 parts
np.linspace(0, 10 , 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.eye(5) # creates a diagonal matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(2,5) # creates an array of random numbers from 0 to 1

array([[0.24537897, 0.45840018, 0.32273305, 0.28235318, 0.39523928],
       [0.80177198, 0.00333554, 0.55108298, 0.36491658, 0.05713947]])

In [27]:
np.random.randn(10) # creates an array of 10 random numbers

array([ 1.63480605,  1.55104114, -1.18858747,  1.28156782,  2.04467061,
        0.35572797,  0.14580076, -1.06380255, -1.76144674,  1.10666133])

In [48]:
np.random.randint(0, 100, 10) # creates an array of 10 random numbers between 0 and 100 excluded

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [52]:
np.random.seed(42) # set a particular set of numbers
np.random.rand(4) # output is always same because of seed

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [73]:
arr = np.random.randint(0, 100, 10)
arr.max() # returns the max value in the array
arr.argmax() # returns the index of the max value in the array
arr.min() # returns the min value in the array
arr.argmin() # returns the index of the min value in the array

np.int64(0)