<a href="https://colab.research.google.com/github/pragyan27bit/ml-learning/blob/main/Day01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]
type(mylist)

list

In [3]:
myarr = np.array(mylist)
type(myarr)

numpy.ndarray

In [4]:
np.arange(1,9,2) # creates an array from 0 till 9 excluded with a gap of 2
np.arange(0, 101, 20) # creates an array from 0 to 100 with a gap of 20

array([  0,  20,  40,  60,  80, 100])

In [5]:
np.zeros(5)
np.zeros((5,5)) # creates a matrix of 5 x 5 of all zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones(5) # creates a array of all elements as 1

array([1., 1., 1., 1., 1.])

In [7]:
np.linspace(0,10,5) # creates an array starting from 0 till 10 included and divides into 5 parts
np.linspace(0, 10 , 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
np.eye(5) # creates a diagonal matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.random.rand(2,5) # creates an array of random numbers from 0 to 1

array([[0.12998505, 0.20253373, 0.44069111, 0.07507178, 0.24489524],
       [0.61804559, 0.20038879, 0.95254942, 0.34538999, 0.45013371]])

In [10]:
np.random.randn(10) # creates an array of 10 random numbers

array([ 0.14585858,  2.14010445,  0.86649968,  2.13543333,  0.71761003,
       -1.17738505,  0.78519263,  0.88249538,  1.20136584,  2.70821442])

In [11]:
np.random.randint(0, 100, 10) # creates an array of 10 random numbers between 0 and 100 excluded

array([21, 25, 61,  3, 97, 36, 66, 98, 23,  1])

In [12]:
np.random.seed(42) # set a particular set of numbers
np.random.rand(4) # output is always same because of seed

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [13]:
arr = np.random.randint(0, 100, 10)
arr.max() # returns the max value in the array
arr.argmax() # returns the index of the max value in the array
arr.min() # returns the min value in the array
arr.argmin() # returns the index of the min value in the array

np.int64(7)

In [14]:
arr[5] # return the value at index 8
# arr[1:5] # returns a subarray from index 1 till 5 excluded
# arr[:5] # returns a subarray from index 0 till 5 excluded
# arr[5:] # returns a subarray from index 5 till end
# arrnew = arr.reshape(2,5)
# arrnew[0,3] # returns the value at given index
# boolarr = arr > 5 # return a boolean array for given condition


np.int64(99)

In [15]:
arr = np.arange(0,10)
arr + 5
np.sqrt(arr) # returns the square root of every. value in the array
np.sin(arr)
np.log(arr)
arr.sum()
arr.mean()
arr.var() # returns variance of teh array
arr.std() # returns standard deviation of array


/tmp/ipykernel_792/72564977.py:5: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


np.float64(2.8722813232690143)

In [16]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d.sum(axis = 0) # axis = 0 is up to down or horizontal axis or across the row
arr2d.sum(axis = 1) # axis = 1 is left to right or vertical axis or across the column

array([ 10,  35,  60,  85, 110])